include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: 
    - '**.config.dart'
    - '**.g.dart'
    - '**.pbenum.dart'
    - '**.pbjson.dart'
    - '**.pbgrpc.dart'
    - '**.pb.dart'

linter:
  rules:
    prefer_single_quotes: true