name: theteam_frontend
summary: 'TheTeam: a tool for modern teams.'
description: |
  TheTeam is the ultimate solution for team management.
  Whether you are a freelancer, a developer, an HR manager, or a headhunter, you can benefit from our powerful and user-friendly application that lets you track time, create reports, manage projects, and more.
  You can access our service from any device and any operating system, and enjoy our beautiful graphs that visualize your progress and performance.
  Plus, if you are an individual user or a small team, you can use our service for free forever. No hidden fees, no strings attached.
  Join TheTeam today and take your team to the next level.
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: '>=3.0.0 <3.1.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  injectable: ^2.1.1
  get_it: ^7.3.0
  go_router: ^7.0.0
  package_info_plus: ^4.0.0
  connectivity_plus: ^4.0.0
  device_info_plus: ^9.0.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  url_launcher: ^6.1.10
  shared_preferences: ^2.1.0
  collection: ^1.17.1
  built_value: ^8.4.3
  built_collection: ^5.1.1
  path_provider: ^2.0.14  
  flutter_native_splash: ^2.2.18
  grpc: ^3.1.0
  dart_jsonwebtoken: ^2.7.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  form_validator: ^2.1.1
  flutter_secure_storage: ^8.0.0
  loading_animations: ^2.2.0
  flutter_flavor: ^3.1.1
  duration: ^3.0.12
  flutter_adaptive_scaffold: ^0.1.3
  local_auth: ^2.1.6
  quick_actions: ^1.0.2
  file_selector: ^0.9.2+4
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  flutter_cache_manager: ^3.3.0
  mixpanel_analytics: ^2.1.1
  logging: ^1.1.1
  fl_chart: ^0.62.0
  data_table_2: ^2.4.2
  dynamic_color: ^1.6.4
  # Desktop
  system_tray: ^2.0.3
  window_manager: ^0.3.2
  launch_at_startup: ^0.2.2
  local_notifier: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  built_value_generator: ^8.4.3
  msix: ^3.11.0

dependency_overrides:
  intl: ^0.18.1
  material_color_utilities: ^0.5.0

flutter:
  uses-material-design: true
  generate: true
  assets:
     - assets/images/

msix_config:
  display_name: TheTeam
  publisher_display_name: DipDev Studio
  identity_name: 55447DipDevStudio.TheTeam
  publisher: CN=955BA76E-FB46-4452-A55A-44043E2AC134
  msix_version: 1.0.0.0
  logo_path: assets/images/logo.png
  languages: en-us
  store: true
  app_installer:
    publish_folder_path: ./
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: true