name: musmula_frontend
description: A Musmula Frontend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  go_router: ^6.2.0
  package_info_plus: ^3.0.3
  connectivity_plus: ^3.0.3
  device_info_plus: ^8.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.18
  collection: ^1.17.0
  built_value: ^8.4.3
  built_collection: ^5.1.1
  file_picker: ^5.2.4
  path_provider: ^2.0.13
  msix: ^3.8.2
  flutter_native_splash: ^2.2.18
  grpc: ^3.1.0
  dart_jsonwebtoken: ^2.7.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  form_validator: ^2.1.1
  flutter_secure_storage: ^8.0.0
  loading_animations: ^2.2.0
  flutter_flavor: ^3.1.1
  duration: ^3.0.12
  flutter_adaptive_scaffold: ^0.1.3
  local_auth: ^2.1.6
  quick_actions: ^1.0.2
  file_selector: ^0.9.2+4
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.4
  built_value_generator: ^8.4.3

flutter:
  uses-material-design: true
  generate: true

msix_config:
  display_name: Musmula
  publisher_display_name: DipDev Studio
  identity_name: 48434MySoftware.MyFlutterApp
  publisher: CN=BF212345-5644-46DF-8668-012044C1B138
  msix_version: 1.0.0.0
  logo_path: assets/images/logo.png
  languages: en-us
  store: true
  app_installer:
    publish_folder_path: ./
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: true