name: musmula_frontend
description: A Musmula Frontend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  go_router: ^6.2.0
  package_info_plus: ^3.0.3
  connectivity_plus: ^3.0.3
  device_info_plus: ^8.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  url_launcher: ^6.1.10
  shared_preferences: ^2.0.18
  collection: ^1.17.0
  built_value: ^8.4.3
  built_collection: ^5.1.1
  file_picker: ^5.2.4
  path_provider: ^2.0.13
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  built_value_generator: ^8.4.3
  msix: ^3.8.2
  flutter_native_splash: ^2.2.18
  grpc: ^3.1.0
  dart_jsonwebtoken: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

msix_config:
  display_name: BZBGEAR Video Switcher
  publisher_display_name: BZBGEAR
  identity_name: 48434MySoftware.MyFlutterApp
  publisher: CN=BF212345-5644-46DF-8668-012044C1B138
  msix_version: 1.0.0.0
  logo_path: assets/images/logo.png
  languages: en-us
  store: true
  app_installer:
    publish_folder_path: d:\
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: true