name: dip-flow
version: 1.0.0
summary: "DIP Flow: a tool for modern teams."
description: |
  DIP Flow is the ultimate solution for team management.
  Whether you are a freelancer, a developer, an HR manager, or a headhunter, you can benefit from our powerful and user-friendly application that lets you track time, create reports, manage projects, and more.
  You can access our service from any device and any operating system, and enjoy our beautiful graphs that visualize your progress and performance.
  Plus, if you are an individual user or a small team, you can use our service for free forever. No hidden fees, no strings attached.
  Join DIP Flow today and take your team to the next level.
confinement: strict
icon: snap/gui/dip-flow.png
base: core18
grade: stable
adopt-info: desktop
contact: info@dip.dev

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  dbus-dip-flow:
    interface: dbus
    bus: session
    name: dev.dip.flow

apps:
  dip-flow:
    command: dip-flow
    extensions: [flutter-master]
    plugs:
      - network
      - network-status
      - password-manager-service
      - home
      - mount-observe
      - desktop
    slots:
      - dbus-dip-flow
parts:
  dip-flow:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    override-build: |
      flutter clean
      flutter pub get
      flutter pub run build_runner build -d
      snapcraftctl build
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - libayatana-appindicator3-dev
      - libnotify-dev
    stage-packages:
      - libjsoncpp-dev
      - libsecret-1-dev
      - libgnome-keyring-common
      - libgnome-keyring0
      - libayatana-appindicator3-dev
      - libnotify-dev
